---
- name: Install Python requirements
  become: yes
  become_method: sudo
  pip: name={{ item }} state=present
  with_items:
    - docker-py
    - passlib

- name: Add docker apt repo
  become: yes
  become_method: sudo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_version }} main'
    state: present

- name: Import the Docker repository key
  become: yes
  become_method: sudo
  apt_key:
    keyserver: p80.pool.sks-keyservers.net
    state: present
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: Install Docker package
  become: yes
  become_method: sudo
  apt:
    name: docker-engine={{ docker_version }}~{{ ubuntu_version }}
    update_cache: yes

- name: Get Distro type
  command: uname -s
  register: distro_type

- name: Get Distro architecture
  command: uname -m
  register: distro_arch

- name: Get Docker Compose
  become: yes
  become_method: sudo
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ distro_type.stdout }}-{{ distro_arch.stdout }}
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: Setup default user with Docker access
  user:
    name: '{{ ansible_ssh_user }}'
    groups: docker
    append: yes

- name: Setup Access to Haystack Registry
  become: no
  docker_login:
    username: '{{ docker_registry_user }}'
    password: '{{ docker_registry_pass }}'
    registry: '{{ docker_registry_url }}'
    email: '{{ docker_registry_email }}'
    reauth: yes
  when: docker_hub_access
